import sys

TMPL = '/sessions/fervent-dreamy-noether/mnt/fpsrdg/scripts/template.html'
with open(TMPL, 'rb') as f:
    content = f.read().decode('utf-8')

START_MARKER = '  // Populate mpt-terr (Territorio'
END_MARKER = '  // Populate inline trend'

start = content.find(START_MARKER)
end = content.find(END_MARKER, start)
if start == -1 or end == -1:
    print('Markers not found', start, end); sys.exit(1)

OLD_BLOCK = content[start:end]
print('Block length:', len(OLD_BLOCK))

NEW_BLOCK = (
    "  // Populate mpt-terr (Territorio — province analysis)\n"
    "  if(p.categoria==='Arbitro'){\n"
    "    try{\n"
    "      const terrEl=document.getElementById('mpt-terr-inner');\n"
    "      if(terrEl){\n"
    "        const arbPv=p.provincia||'';\n"
    "        // Province di competenza: SS e NU condivise\n"
    "        const pvComp=new Set([arbPv]);\n"
    "        if(arbPv==='SS')pvComp.add('NU');\n"
    "        if(arbPv==='NU')pvComp.add('SS');\n"
    "        // Gare arbitrate (usa gare_arbitro: .h=casa, .a=ospite, .campo, .d=data, .c=camp)\n"
    "        const gaArb=p.gare_arbitro||[];\n"
    "        const sqVisitate=new Set();\n"
    "        // Squadre di FUORI area che l'arbitro HA arbitrato\n"
    "        const sqFuoriArea=new Set();\n"
    "        const campiVisitati=new Set();\n"
    "        // Gare giocate fuori dalla propria provincia (arbPv)\n"
    "        const gareFuoriPv=[];\n"
    "        gaArb.forEach(g=>{\n"
    "          const h=g.h||'',a=g.a||'',campo=(g.campo||g['Campo']||'').trim();\n"
    "          if(h){sqVisitate.add(h);const pvH=(SQ[h]||{}).prov||'';if(pvH&&!pvComp.has(pvH))sqFuoriArea.add(h);}\n"
    "          if(a){sqVisitate.add(a);const pvA=(SQ[a]||{}).prov||'';if(pvA&&!pvComp.has(pvA))sqFuoriArea.add(a);}\n"
    "          if(campo){\n"
    "            campiVisitati.add(campo.toLowerCase());\n"
    "            const pvC=cpv(campo);\n"
    "            if(pvC&&pvC!==arbPv)gareFuoriPv.push(g);\n"
    "          }\n"
    "        });\n"
    "        // Squadre nelle province di competenza\n"
    "        const sqDiComp=Object.entries(SQ).filter(([n,s])=>pvComp.has(s.prov||'')).map(([n])=>n);\n"
    "        const sqNonVisitate=sqDiComp.filter(n=>!sqVisitate.has(n));\n"
    "        // Campi nelle province di competenza non visitati\n"
    "        const campiDiComp=Object.values(D.campi||{}).filter(c=>pvComp.has(c.prov||''));\n"
    "        const campiNonVisitati=campiDiComp.filter(c=>!campiVisitati.has((c.campo||'').trim().toLowerCase()));\n"
    "        // Helper pill squadra\n"
    "        function sqPill(nome,clr){\n"
    "          const s=SQ[nome]||{};\n"
    "          const ns=nome.replace(/\\x27/g,'\\\\x27');\n"
    "          return '<span style=\"display:inline-flex;align-items:center;gap:3px;background:'+clr+'18;border:1px solid '+clr+'44;border-radius:5px;padding:2px 7px;font-size:.65rem;margin:2px;cursor:pointer\" onclick=\"openSquadra(\\''+ns+'\\')\"><b style=\"color:'+clr+'\">'+escH(nome)+'</b></span>';\n"
    "        }\n"
    "        const pvLabel=[...pvComp].sort().join(' + ');\n"
    "        let html='<div style=\"font-size:.72rem;color:var(--mu);margin-bottom:14px\">Province di competenza: <b>'+pvLabel+'</b>'+(arbPv==='SS'?' (include NU per accordo territoriale)':arbPv==='NU'?' (include SS per accordo territoriale)':'')+'</div>';\n"
    "\n"
    "        // ── SEZ A: Squadre NON arbitrate in provincia (tabella con categoria) ──\n"
    "        html+='<div style=\"margin-bottom:18px\">';\n"
    "        html+='<div style=\"font-size:.75rem;font-weight:700;color:#c0392b;margin-bottom:8px\">';\n"
    "        html+='\u274c Squadre NON ancora arbitrate ('+pvLabel+') <span style=\"font-size:.65rem;font-weight:400;color:var(--mu)\">'+sqNonVisitate.length+' su '+sqDiComp.length+'</span></div>';\n"
    "        if(sqNonVisitate.length===0){\n"
    "          html+='<div style=\"color:var(--green);font-size:.72rem;padding:6px 10px;background:#e6f8ee;border-radius:6px\">\u2705 Tutte le squadre della provincia arbitrate almeno una volta!</div>';\n"
    "        }else{\n"
    "          const byCamp={};\n"
    "          sqNonVisitate.forEach(n=>{\n"
    "            const s=SQ[n]||{};\n"
    "            const camps=Object.keys(s.campionati||{});\n"
    "            const camp=camps.length?camps.sort((a,b)=>(s.campionati[b]||0)-(s.campionati[a]||0))[0]:'Sconosciuto';\n"
    "            const pv=s.prov||'?';\n"
    "            const key=camp+'||'+pv;\n"
    "            if(!byCamp[key])byCamp[key]={camp,pv,sqs:[]};\n"
    "            byCamp[key].sqs.push(n);\n"
    "          });\n"
    "          html+='<table style=\"width:100%;border-collapse:collapse;font-size:.72rem\">';\n"
    "          html+='<thead><tr style=\"background:#fff0f0\"><th style=\"padding:4px 8px;text-align:left;border-bottom:1px solid #f5c6c6\">Campionato</th><th style=\"padding:4px 8px;text-align:left;border-bottom:1px solid #f5c6c6\">Prov.</th><th style=\"padding:4px 8px;text-align:left;border-bottom:1px solid #f5c6c6\">Squadre</th></tr></thead><tbody>';\n"
    "          Object.keys(byCamp).sort().forEach(key=>{\n"
    "            const {camp,pv,sqs}=byCamp[key];\n"
    "            const clr=PC[pv]||campColor(camp)||'#555';\n"
    "            html+='<tr style=\"border-bottom:1px solid #fce8e8;vertical-align:top\">';\n"
    "            html+='<td style=\"padding:4px 8px;font-size:.68rem;white-space:nowrap\"><span style=\"'+campBadgeStyle(camp)+'border-radius:3px;padding:1px 6px;font-size:.62rem\">'+escH(camp)+'</span></td>';\n"
    "            html+='<td style=\"padding:4px 8px\"><span style=\"background:'+clr+';color:#fff;border-radius:3px;padding:0 5px;font-size:.62rem;font-weight:700\">'+pv+'</span></td>';\n"
    "            html+='<td style=\"padding:3px 8px\">'+sqs.sort().map(n=>sqPill(n,clr)).join('')+'</td>';\n"
    "            html+='</tr>';\n"
    "          });\n"
    "          html+='</tbody></table>';\n"
    "        }\n"
    "        html+='</div>';\n"
    "\n"
    "        // ── SEZ B: Squadre arbitrate che NON risiedono in pvComp ──\n"
    "        html+='<div style=\"margin-bottom:18px\">';\n"
    "        html+='<div style=\"font-size:.75rem;font-weight:700;color:#6f42c1;margin-bottom:8px\">';\n"
    "        html+='\U0001f30d Squadre di FUORI area arbitrate <span style=\"font-size:.65rem;font-weight:400;color:var(--mu)\">'+sqFuoriArea.size+' squadre</span></div>';\n"
    "        if(sqFuoriArea.size===0){\n"
    "          html+='<div style=\"color:var(--mu);font-size:.72rem;padding:6px 10px;background:#f8faff;border-radius:6px\">Nessuna squadra fuori area arbitrata.</div>';\n"
    "        }else{\n"
    "          const byPvF={};\n"
    "          [...sqFuoriArea].forEach(n=>{const pv2=(SQ[n]||{}).prov||'?';if(!byPvF[pv2])byPvF[pv2]=[];byPvF[pv2].push(n);});\n"
    "          Object.entries(byPvF).sort().forEach(([pv2,sqs])=>{\n"
    "            const clr=PC[pv2]||'#555';\n"
    "            html+='<div style=\"margin-bottom:6px\"><span style=\"background:'+clr+';color:#fff;border-radius:4px;padding:1px 7px;margin-right:4px;font-size:.62rem;font-weight:700\">'+pv2+'</span>';\n"
    "            html+=sqs.sort().map(n=>sqPill(n,clr)).join('');\n"
    "            html+='</div>';\n"
    "          });\n"
    "        }\n"
    "        html+='</div>';\n"
    "\n"
    "        // ── SEZ C: Gare disputate fuori dalla propria provincia (arbPv) ──\n"
    "        html+='<div style=\"margin-bottom:18px\">';\n"
    "        html+='<div style=\"font-size:.75rem;font-weight:700;color:#e67e22;margin-bottom:8px\">';\n"
    "        html+='\U0001f3df\ufe0f Gare fuori dalla provincia '+arbPv+' <span style=\"font-size:.65rem;font-weight:400;color:var(--mu)\">'+gareFuoriPv.length+' gare</span></div>';\n"
    "        if(gareFuoriPv.length===0){\n"
    "          html+='<div style=\"color:var(--mu);font-size:.72rem;padding:6px 10px;background:#fff8f0;border-radius:6px\">Nessuna gara fuori dalla provincia '+arbPv+'.</div>';\n"
    "        }else{\n"
    "          html+='<div style=\"overflow-x:auto\"><table style=\"width:100%;border-collapse:collapse;font-size:.72rem\">';\n"
    "          html+='<thead><tr style=\"background:#fff8f0\"><th style=\"padding:4px 8px;text-align:left;border-bottom:1px solid #ffe0b2\">Data</th><th style=\"padding:4px 8px;text-align:left;border-bottom:1px solid #ffe0b2\">Campo</th><th style=\"padding:4px 8px;text-align:left;border-bottom:1px solid #ffe0b2\">Prov.</th><th style=\"padding:4px 8px;text-align:left;border-bottom:1px solid #ffe0b2\">Casa</th><th style=\"padding:4px 8px;text-align:left;border-bottom:1px solid #ffe0b2\">Ospite</th><th style=\"padding:4px 8px;text-align:left;border-bottom:1px solid #ffe0b2\">Campionato</th></tr></thead><tbody>';\n"
    "          gareFuoriPv.sort((a,b)=>(a.d||'').localeCompare(b.d||'')).forEach((g,i)=>{\n"
    "            const pvG=cpv(g.campo||g['Campo']||'')||'?';\n"
    "            const clr=PC[pvG]||'#888';\n"
    "            html+='<tr style=\"background:'+(i%2?'#fffaf5':'#fff')+';border-bottom:1px solid #ffe0b2\">';\n"
    "            html+='<td style=\"padding:3px 8px;white-space:nowrap\">'+(g.d||g['Data']||'')+'</td>';\n"
    "            html+='<td style=\"padding:3px 8px;font-size:.67rem\">'+escH(g.campo||g['Campo']||'\u2014')+'</td>';\n"
    "            html+='<td style=\"padding:3px 8px\"><span style=\"background:'+clr+';color:#fff;border-radius:3px;padding:0 5px;font-size:.62rem;font-weight:700\">'+pvG+'</span></td>';\n"
    "            html+='<td style=\"padding:3px 8px;font-size:.68rem\">'+escH(g.h||'')+'</td>';\n"
    "            html+='<td style=\"padding:3px 8px;font-size:.68rem\">'+escH(g.a||'')+'</td>';\n"
    "            html+='<td style=\"padding:3px 8px;font-size:.65rem\">'+escH(g.c||g['Campionato']||'')+'</td>';\n"
    "            html+='</tr>';\n"
    "          });\n"
    "          html+='</tbody></table></div>';\n"
    "        }\n"
    "        html+='</div>';\n"
    "\n"
    "        // ── SEZ D: Campi in pvComp non ancora visitati ──\n"
    "        html+='<div style=\"margin-bottom:8px\">';\n"
    "        html+='<div style=\"font-size:.75rem;font-weight:700;color:#16a085;margin-bottom:8px\">';\n"
    "        html+='\U0001f3df\ufe0f Campi in '+pvLabel+' non ancora visitati <span style=\"font-size:.65rem;font-weight:400;color:var(--mu)\">'+campiNonVisitati.length+' su '+campiDiComp.length+'</span></div>';\n"
    "        if(campiNonVisitati.length===0){\n"
    "          html+='<div style=\"color:var(--green);font-size:.72rem;padding:6px 10px;background:#e6f8ee;border-radius:6px\">\u2705 Hai visitato tutti i campi della provincia!</div>';\n"
    "        }else{\n"
    "          const byPvD={};\n"
    "          campiNonVisitati.forEach(c=>{const pv3=c.prov||'?';if(!byPvD[pv3])byPvD[pv3]=[];byPvD[pv3].push(c);});\n"
    "          Object.entries(byPvD).sort().forEach(([pv3,cs])=>{\n"
    "            const clr=PC[pv3]||'#555';\n"
    "            html+='<div style=\"margin-bottom:6px\"><span style=\"background:'+clr+';color:#fff;border-radius:4px;padding:1px 7px;margin-right:4px;font-size:.62rem;font-weight:700\">'+pv3+'</span>';\n"
    "            html+=cs.sort((a,b)=>(a.campo||'').localeCompare(b.campo||'')).map(c=>{\n"
    "              return '<span style=\"display:inline-flex;align-items:center;background:'+clr+'12;border:1px solid '+clr+'33;border-radius:5px;padding:2px 8px;font-size:.65rem;margin:2px\"><b style=\"color:'+clr+'\">'+escH(c.campo||'')+'</b></span>';\n"
    "            }).join('');\n"
    "            html+='</div>';\n"
    "          });\n"
    "        }\n"
    "        html+='</div>';\n"
    "\n"
    "        terrEl.innerHTML=html;\n"
    "      }\n"
    "    }catch(e){const el=document.getElementById('mpt-terr-inner');if(el)el.innerHTML='<p style=\"color:red;padding:10px\">Errore territorio: '+e.message+'</p>';}\n"
    "  }\n\n"
)

content = content[:start] + NEW_BLOCK + content[end:]

with open(TMPL, 'w', encoding='utf-8') as f:
    f.write(content)

print('Territorio rewritten. File size:', len(content))
